### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by gooseleggs** [estebanthi/ObsidianTemplateVaultV2#1]
I have downloaded this template to see if it will work for me.  Unfortunately, I got stuck at trying to enter notes, because I tried to start with a capital t (T).  Took me ages to figure out what was wrong.  

In the hotkeys.js, there are a number of hot keys that only use the Shift key.  Therefore, trying to type the letter (say capital T) does not type the character, but rather open the _Insert Template_ menu.

It also has VIM key bindings enabled by default.  This is confusing as to why you cannot type straight away without having to enter _insert_ or _i_.

**Comment by estebanthi** [comment]
Actually, I rarely use the Shift key to type capitals so I preferred using it for shortcuts. About the VIM key bindings, this is also a personal preference. Keep in mind this template vault is tailored to my needs, in the end this is just a public version of my vault, that's why the keybindings may be strange for an average person.

I think I'll add a disclaimer to tell people to have a look at the keybindings before using the vault, and to specify the VIM mode is enabled by default, it could have avoided confusion and saved you some time!

**Comment by gooseleggs** [comment]
Happy with the disclaimer. Do you have something doing auto caps?  Do you think you could add an example of hierarchy of documents with MOCs. I am not sure if the best way to do this so I have created MOCs with name of moc_subject. How do you do it. I am looking at doing a knowledge base. Maybe have a moc called moc_kb and then use tags for each different subject?

**Comment by estebanthi** [comment]
I just use caps lock every time I need to type caps even if it is a single capital, I don't have something doing auto caps.

I would not recommend using tags for different subjects. It works, but you'll end up with a large number of tags, so it's up to you to decide, but personally I prefer doing things differently using properties and Dataview. There is an example of how I do it in the template vault.

About the hierarchy of subjects, it's up to you to decide how specific you want your MOCs to be, and it depends on what you need. I used to have many nested MOCs (e.g., a MOC "Science", containing MOCs such as "Aeronautics", containing MOCs such as "Aeronautic Regulations"). Now, my setup is simpler and I don't go this specific.
